version: "3"

vars:
  COMP_TIME:
    sh: printf 'constant.compileTime=%s' "$(date -u -Iseconds)"

tasks:
  clean:
    cmd: go clean -r -cache -testcache -modcache

  tidy:
    cmd: go mod tidy -v -x

  clear-build-dir:
    cmds:
      - cmd: rm -rf ./bin
      - cmd: mkdir -p ./bin

  build:
    requires:
      vars:
        - COMP_TIME
    cmds:
      - task: clear-build-dir
      - cmd: |-
          go build \
            -buildvcs=true \
            -trimpath \
            -ldflags="-compressdwarf=true -extldflags=-static -s -w -buildid='' -X '{{.COMP_TIME}}'" \
            -o ./bin/tgtd \
            ./cmd

  lint:
    internal: true
    requires:
      vars:
        - OUT_FORMAT
    cmd: |-
      go tool \
        github.com/golangci/golangci-lint/cmd/golangci-lint \
        run {{ if .FIX }}--fix {{ end }}\
        --print-resources-usage \
        --out-format="{{.OUT_FORMAT}}"

  lint:local:
    cmds:
      - task: lint
        vars:
          OUT_FORMAT: colored-line-number

  lint:local:fix:
    cmds:
      - task: lint
        vars:
          OUT_FORMAT: colored-line-number
          FIX: true

  lint:ci:
    cmds:
      - task: lint
        vars:
          OUT_FORMAT: colored-line-number
