version: "3"

vars:
  GOLANGCI_LINT_VERSION: v2.2.0
  COMP_TIME:
    sh: printf 'constant.compileTime=%s' "$(date -u -Iseconds)"

tasks:
  clean:
    cmd: go clean -r -cache -testcache -modcache

  tidy:
    cmd: go mod tidy -v -x

  clear-build-dir:
    cmds:
      - cmd: rm -rf ./bin
      - cmd: mkdir -p ./bin

  build:
    requires:
      vars:
        - COMP_TIME
    cmds:
      - task: clear-build-dir
      - cmd: |-
          go build \
            -buildvcs=true \
            -trimpath \
            -ldflags="-compressdwarf=true -extldflags=-static -s -w -buildid='' -X '{{.COMP_TIME}}'" \
            -o ./bin/tgtd \
            ./cmd

  install-linter:
    status:
      - test "$(./tools/golangci-lint version --short)" = '{{trimPrefix "v" .GOLANGCI_LINT_VERSION}}'
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b ./tools {{.GOLANGCI_LINT_VERSION}}

  lint:
    internal: true
    deps:
      - task: install-linter
    cmd: |-
      ./tools/golangci-lint \
        run {{ if .FIX }}--fix {{ end }}\
        --print-resources-usage \
        --output.text.path stdout

  lint:local:
    cmds:
      - task: lint

  lint:local:fix:
    cmds:
      - task: lint
        vars:
          FIX: true

  lint:ci:
    cmds:
      - task: lint
