name: tgtd
services:
  tgtd:
    image: ghcr.io/xeptore/tgtd:edge
    pull_policy: always
    command:
      - run
      - --config
      - /home/nonroot/config.yml
    container_name: tgtd
    restart: unless-stopped
    networks:
      - tgtd
    stop_signal: SIGINT
    stop_grace_period: 5s
    init: true
    volumes:
      - type: bind
        source: ./config.yml
        target: /home/nonroot/config.yml
        read_only: true
      - type: bind
        # To create this directory, run `install -d -m 0700 -o 1000 -g 1000 ./downloads`
        source: ./downloads
        target: /home/nonroot/downloads
        bind:
          propagation: shared
          create_host_path: false
      - type: bind
        # To create this directory, run `install -d -m 0700 -o 1000 -g 1000 ./.creds`
        source: ./.creds
        target: /home/nonroot/.creds
        bind:
          propagation: shared
          create_host_path: false
    env_file:
      - .env
networks:
  tgtd:
    name: tgtd
    driver: bridge
volumes:
  default:
    name: tgtd
