name: tgtd
services:
  tgtd:
    image: ghcr.io/xeptore/tgtd:edge
    pull_policy: always
    command:
      - run
      - --config
      - /home/nonroot/config.yml
    container_name: tgtd
    restart: unless-stopped
    networks:
      - tgtd
    stop_signal: SIGINT
    stop_grace_period: 5s
    init: true
    volumes:
      - type: bind
        source: ./config.yml
        target: /home/nonroot/config.yml
        read_only: true
      - type: tmpfs
        target: /home/nonroot/.certs
        tmpfs:
          size: 10m
          mode: 755
    env_file:
      - .bot.env
networks:
  tgtd:
    name: tgtd
    driver: bridge
